services:
  webdev:
    build:
      context: ./cartogram-web/
      dockerfile: Dockerfile
    image: gocartio/cartogram-web${TAG}
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - CARTOGRAM_DEBUG=TRUE
      - CARTOGRAM_DATABASE_URI=postgresql://cartogram:password@postgres/cartogram
    command: development
    ports:
      - "5005:5000"
      - "5173:5173"
    volumes:
      - ./cartogram-web:/root
      - ./data/userdata:/root/internal/static/userdata
      - ./data/tmp:/root/internal/tmp

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cartogram
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
