FROM python:3-stretch

COPY ./cartogram-web/internal /root/internal
COPY ./cartogram-web/data /root/data

RUN pip install --upgrade pip
RUN pip install -r /root/internal/requirements.txt

COPY ./sources.list /etc/apt/
RUN apt-get update && apt-get -y install cron
RUN (crontab -l ; echo "0 0 * * * curl http://localhost:5000/cleanup") | crontab

EXPOSE 5000
WORKDIR /root/internal