FROM python:3-stretch

COPY ./cartogram-web/internal /root/internal
COPY ./cartogram-web/data /root/data

RUN pip install --upgrade pip
RUN pip install -r /root/internal/requirements.txt

EXPOSE 5000
WORKDIR /root/internal