name: Pull latest gocartio/cartogram-web image on host (go-cart.io)

on:
  # only when triggered manually, after we have tested it ourselves
  workflow_dispatch:
  push:
    branches: [ "main", "create-github-action-to-pull-new-image" ]

jobs:
  pull-new-cartogram-web-image:
    runs-on: ubuntu-latest
    steps:
      - name: Run tmate
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Calculate SHORT_SHA
        id: vars
        run:
          echo "SHORT_SHA=$(git -C cartogram-web/ rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Pull new web image on go-cart.io server
        uses: appleboy/ssh-action@v1.1.0
        env:
          TAG: ":${{ steps.vars.outputs.SHORT_SHA }}"
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: cartogram
          key: ${{ secrets.SERVER_SSH_ACCESS_KEY }}
          envs: TAG
          script: |
            # Pull gocartio/cartogram-web:SHORT_SHA
            docker compose -f ~/cartogram-docker/docker-compose.yml pull web
            docker compose -f ~/cartogram-docker/docker-compose.yml up -d --no-deps web

            # Making sure the correct image was pulled
            docker inspect --format='{{.Config.Image}}' cartogram-docker-web-1

            # Sanity check by finding out the version of `cartogram-cpp`
            CPP_VERSION=$(docker exec cartogram-docker-web-1 executable/cartogram --version)
            echo "cartogram-cpp version: $CPP_VERSION"
