name: Pull latest gocartio/cartogram-web image on host (go-cart.io)

on:
  # only when triggered manually, after we have tested it ourselves
  workflow_dispatch:
  push:
    branches: [ "main", "create-github-action-to-pull-new-image" ]

jobs:
  pull-new-cartogram-web-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        env:
          HOST: ${{ secrets.SERVER_HOSTNAME }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          KEY: ${{ secrets.SERVER_SSH_ACCESS_KEY }}
        run: |
          ECHO $HOST > HOST.TXT
          echo $USERNAME > username.txt
          echo "$KEY" > key.txt

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_ACCESS_KEY }}

      - name: Execute commands over SSH
        env:
          HOST: ${{ secrets.SERVER_HOSTNAME }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            docker-compose -f /home/cartogram/cartogram-docker/docker-compose.yml pull web
            docker-compose -f /home/cartogram/cartogram-docker/docker-compose.yml up -d --no-deps web
          EOF

      - name: Run tmate
        uses: mxschmitt/action-tmate@v3